Generics power!
emvakar/EKKeychainService pull request #7
Opened 2021-06-29 15:41 UTC by DmitriyTor

More comfortable (don't look at the tests)

And you can save your custom codable struct

2021-06-29 15:41 UTC, DmitriyTor commented on Sources/EKKeychainService/EKKeychainService.swift
> +    public func set<T: Codable>(_ object: T?, withKey key: EKFieldKey) throws {
holy shit, throws need to be removed

2021-07-03 18:08 UTC, emvakar requested changes
You need to supplement and correct the tests and then ill merge it

2021-07-04 14:02 UTC, DmitriyTor commented
тесты разве не взлетели?

2021-07-05 10:31 UTC, merged

2021-07-05 10:36 UTC, emvakar commented
> тесты разве не взлетели?

travis почему-то не запустил их и не чекнул